### PR TITLE
Make class channels better.

### PR DESCRIPTION
**Pull request by jgcodes2020**
Class channel topics should have topics with a slightly richer name:

for example
```
ENG1D1 => Grade 9 Academic English
TDJ2O1 => Grade 10 Tech Design
ESLAO1 => ESL A
```

Names are not affected, only topics. I found having the course code be the name and topic a little too bland and boring.

-Jacky Guo

### CODE REVIEW

**Review by Ynng — CHANGES_REQUESTED** [review]
for decodeCourseType, O stands for Open and X stands for Dual Credit

addcourse.js identifies the class channels using the topic, it should be using the channel name instead (line 238)
consider applying the changes in course_list.json to course_list_simplified.txt under temp as well.

**Comment by jgcodes2020** [comment]
The reason O and X are unnamed are because I didn't want to have "Grade 9 Open Phys-ed" or "Grade 12 Dual-Credit Co-op". I'll move it to be an internal function.

**Comment by Ynng** [comment]
Yhea but then there are "Open French" FSF1O1, which is different from FSF1D1 Academic French.
Actually just make a special case for that I guess. I can't think of any other similar situations.

**Comment by jgcodes2020** [comment]
Open French I believe is taken care of by the course list itself.

```json
"FSF1O1": {
    "department": "Grade 9 French",
    "name": "Open French",
    "grade": 1,
    "dedicated_chat": true
  },
```
Since `name` is Open French, it should say Grade 9 Open French.

**Comment by Ynng** [comment]
Have you tested out the commands on a bot yet? If not I'll merge after I test it in a test server tomorrow.

**Pull request merged**
