### PR TITLE
Added timeout for addcourse

### PR DESCRIPTION
**Pull request by KureYv**

### CODE REVIEW

**Comment by KureYv** [comment]
Haven't done removecourse cause might not work

**Comment by Ynng** [comment]
I already editted and got removecourse to work. Also I just changed addcourse a lot and there are some merge conflicts....

**Comment by KureYv** [comment]
Oh I'm just saying that idk if the timeout works so I'm not gonna add it on removecourse, also thanks for getting removecourse to work i can't rlly debug it

**Comment by Ynng** [comment]
you just have to create your own discord bot, and then paste the token into tokens.json under the root direction, in json format

```json
{
   token: "pastehere"
}```

**Pull request merged**
